site_name: DiamanteDesk Documentation
theme: readthedocs
extra_css: ['css/extra.css']
pages:
- Home: 'index.md' 
- Installation Guide:
    - 'Installation': 'installation-guide/installation.md'
- User Guide:
    - 'Branches': 'user-guide/branches.md'
    - 'Tickets': 'user-guide/tickets.md'
    - 'User Management': 'user-guide/user-management.md'
    - 'Tagging': 'user-guide/tagging.md'
    - 'Channels': 'user-guide/channels/channels.md'
    - 'Processing Emails': 'user-guide/channels/email-processing.md'
    - 'Portal': 'user-guide/channels/portal.md'
    - 'Embedded Form': 'user-guide/channels/embedded-form.md'
- Developer Guide:
    - 'Contributing': 'developer-guide/contributing.md'
    - 'RESTful API Guide': 'developer-guide/restful-api-guide.md'
- Integration:
    - 'API Credentials': 'integration/api-credentials.md'
    - 'Magento': 'integration/magento.md'
    - 'WordPress': 'integration/wordpress.md'
    - 'Prestashop': 'integration/prestashop.md'    
